# Generated by Django 5.1.1 on 2025-02-11 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
