# Generated by Django 5.1.1 on 2025-02-12 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_category_name_alter_product_name'),
        ('api', '0009_product_colors_product_rating_product_sizes_and_more'),
    ]

    operations = [
    ]
