# Generated by Django 5.1.1 on 2025-02-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_user_city_user_country_user_dob_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('staff', 'Staff')], default='user', max_length=10),
        ),
    ]
