# Generated by Django 5.1.1 on 2025-03-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('primary_main', models.CharField(default='#D6056A', max_length=7)),
                ('secondary_main', models.CharField(default='#800080', max_length=7)),
                ('background_default', models.CharField(default='#F8FAFC', max_length=7)),
                ('background_paper', models.CharField(default='#FFFFFF', max_length=7)),
                ('black_main', models.CharField(default='#000000', max_length=7)),
                ('black_light', models.CharField(default='#FFFFFF', max_length=7)),
            ],
        ),
    ]
