# Generated by Django 5.1.1 on 2025-03-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_settings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='primary_main',
            new_name='Primary',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='secondary_main',
            new_name='Secondary',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='background_default',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='background_paper',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='black_light',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='black_main',
        ),
        migrations.AddField(
            model_name='settings',
            name='Danger',
            field=models.CharField(default='#dc3545', max_length=7),
        ),
        migrations.AddField(
            model_name='settings',
            name='Info',
            field=models.CharField(default='#007bff', max_length=7),
        ),
        migrations.AddField(
            model_name='settings',
            name='Success',
            field=models.CharField(default='#28a745', max_length=7),
        ),
        migrations.AddField(
            model_name='settings',
            name='Warning',
            field=models.CharField(default='#ffc107', max_length=7),
        ),
    ]
