# Generated by Django 5.1.1 on 2025-03-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_primary_main_settings_primary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='mode',
            field=models.CharField(choices=[('light', 'light'), ('dark', 'dark')], default='light', max_length=10),
        ),
    ]
