# Generated by Django 5.1.1 on 2025-03-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_settings_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='Danger',
            new_name='danger',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='Info',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='Primary',
            new_name='primary',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='Secondary',
            new_name='secondary',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='Success',
            new_name='success',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='Warning',
            new_name='warning',
        ),
        migrations.AddField(
            model_name='settings',
            name='Grey',
            field=models.CharField(default='#787671', max_length=7),
        ),
    ]
